[workspace]
resolver = "2"
members = [
    "client",
    "bookapp",
]

[workspace.dependencies]
axum = { version = "0.7.7" }
tower = "0.5.1"
reqwest = "0.12.7"
opentelemetry = "0.26.0"
tracing = { version = "0.1.40" }
tracing-opentelemetry = { version = "0.27.0" }
