[workspace]
resolver = "2"
members = [
    "client",
    "bookapp",
]

[workspace.dependencies]
axum = { version = "0.8" }
tower = "0.5.1"
reqwest = "0.12.7"
opentelemetry = "0.27.1"
tracing = { version = "0.1.41" }
tracing-opentelemetry = { version = "0.28.0" }
